error_log /dev/stderr debug;
access_log /dev/stdout;

server {
	listen 443 ssl;

	ssl_certificate /etc/ssl/certs/insrv5.net.crt;
	ssl_certificate_key /etc/ssl/certs/insrv5.net.key;

	server_name insrv5.net www.insrv5.net;

	error_page 404 = /error404;
	error_page 401 = https://insrv5.net/users/index.php?return=$scheme://$host$request_uri;

	location ^~ /errors/ {
        return 404; 
    }
	
	location /apps {
        deny all;
        return 404;
    }

	location = /logout {
		auth_request off;
		
		proxy_pass http://192.168.51.2/users/logout.php;
		
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location = /error404 {
		internal;
		proxy_pass http://192.168.51.2/errors/404.html;
	}


	location / {
		proxy_pass http://192.168.5.2/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}

server {
	listen 80;
	server_name insrv5.net www.insrv5.net;

	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;

	ssl_certificate /etc/ssl/certs/insrv5.net.crt;
	ssl_certificate_key /etc/ssl/certs/insrv5.net.key;

	server_name vpn.insrv5.net;

	location / {
		proxy_pass http://192.168.5.20:51821/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}

server {
	listen 80;
	server_name vpn.insrv5.net;

	return 301 https://$host$request_uri;
}